name: Build CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildCI

      - name: Upload CI
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*.json
          if-no-files-found: error
